In [4]:
import warnings

In [5]:
warnings.filterwarnings('ignore')

In [6]:
pip install tensorflow

In [7]:
from tensorflow import keras

In [8]:
from keras.layers import Input, Lambda, Dense, Flatten

In [9]:
from keras.models import Model
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

In [12]:
IMAGE_SIZE = [224, 224]

train_path = r'C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray\train'
valid_path = r'C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray\test'

In [13]:
vgg = VGG16(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)


In [14]:
for layer in vgg.layers:
    layer.trainable = False

In [15]:
folders = glob(r'C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray\train\*')
x = Flatten()(vgg.output)

In [16]:
prediction = Dense(len(folders), activation='softmax')(x)
# create a model object
model = Model(inputs=vgg.input, outputs=prediction)
# view the structure of the model
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [17]:
model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

In [18]:
from keras.preprocessing.image import ImageDataGenerator

In [19]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)




# Make sure you provide the same target size as initialied for the image size
training_set = train_datagen.flow_from_directory(r"C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray\train",
                                                 target_size = (224, 224),
                                                 batch_size = 10,
                                                 class_mode = 'categorical')




test_set = test_datagen.flow_from_directory(r"C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray\test",
                                            target_size = (224, 224),
                                            batch_size = 10,
                                            class_mode = 'categorical')

Found 5216 images belonging to 2 classes.
Found 624 images belonging to 2 classes.


In [23]:
# Correct the syntax by using model.fit
r = model.fit(
    training_set,
    validation_data=test_set,
    epochs=1,  # Number of epochs
    steps_per_epoch=len(training_set),  # Use steps per epoch based on your dataset size
    validation_steps=len(test_set)  # Validation steps based on the test dataset
)


522/522 [==============================] - 1411s 3s/step - loss: 0.2032 - accuracy: 0.9271 - val_loss: 0.3202 - val_accuracy: 0.9103


In [24]:
import tensorflow as tf
from keras.models import load_model

model.save(r"C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray.h5")

In [25]:
from keras.models import load_model

In [26]:
from keras.preprocessing import image

In [27]:
from keras.applications.vgg16 import preprocess_input

In [28]:
import numpy as np

In [29]:
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

# Load the model (assuming you have a model architecture already saved)
model = load_model(r"C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray.h5")

# If you're creating a model from scratch, ensure the input shape is defined
# Example CNN model (in case you need a reference)
model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))  # Define input shape for images
model.add(MaxPooling2D(pool_size=(2, 2)))

# Add more Conv/Pooling layers as needed
# Finally, add Flatten and Dense layers
model.add(Flatten())  # Flatten 2D output to 1D
model.add(Dense(128, activation='relu'))  # Fully connected layer
model.add(Dense(2, activation='softmax'))  # Output layer for 2 classes

model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# Fit the model or load weights
r = model.fit_generator(
    training_set,
    validation_data=test_set,
    epochs=1,
    steps_per_epoch=len(training_set),
    validation_steps=len(test_set)
)


522/522 [==============================] - 355s 675ms/step - loss: 0.7882 - accuracy: 0.8512 - val_loss: 0.8969 - val_accuracy: 0.7099


In [32]:
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

# Load the model (assuming you have a model architecture already saved)
model = load_model(r"C:\Users\rumjhum\Desktop\Pneumonia Detection\archive\chest_xray")

# If you're creating a model from scratch, ensure the input shape is defined
# Example CNN model (in case you need a reference)
model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))  # Define input shape for images
model.add(MaxPooling2D(pool_size=(2, 2)))

# Add more Conv/Pooling layers as needed
# Finally, add Flatten and Dense layers
model.add(Flatten())  # Flatten 2D output to 1D
model.add(Dense(128, activation='relu'))  # Fully connected layer
model.add(Dense(2, activation='softmax'))  # Output layer for 2 classes

model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# Fit the model or load weights
r = model.fit_generator(
    training_set,
    validation_data=test_set,
    epochs=1,
    steps_per_epoch=len(training_set),
    validation_steps=len(test_set)
)


522/522 [==============================] - 320s 609ms/step - loss: 0.5334 - accuracy: 0.8752 - val_loss: 0.8290 - val_accuracy: 0.7708


In [30]:
img=image.load_img(r"C:\Users\rumjhum\Desktop\Pneumonia Detection\chest_xray\val\NORMAL\NORMAL2-IM-1427-0001.jpeg",target_size=(224,224))


In [32]:
x=image.img_to_array(img)


In [33]:
x=np.expand_dims(x, axis=0)
img_data=preprocess_input(x)
classes=model.predict(img_data)

In [34]:
result=int(classes[0][0])


In [35]:
if result==0:
    print("Person is Affected By PNEUMONIA")
else:
    print("Result is Normal")

Result is Normal


In [36]:
import PIL

In [37]:
print(x)

[[[[-117.68     -110.779     -97.939   ]
   [-123.68     -116.779    -103.939   ]
   [-116.68     -109.779     -96.939   ]
   ...
   [ -45.68      -38.779     -25.939003]
   [ -49.68      -42.779     -29.939003]
   [ -56.68      -49.779     -36.939003]]

  [[-123.68     -116.779    -103.939   ]
   [-121.68     -114.779    -101.939   ]
   [-112.68     -105.779     -92.939   ]
   ...
   [ -41.68      -34.779     -21.939003]
   [ -54.68      -47.779     -34.939003]
   [ -59.68      -52.779     -39.939003]]

  [[-123.68     -116.779    -103.939   ]
   [-118.68     -111.779     -98.939   ]
   [-111.68     -104.779     -91.939   ]
   ...
   [ -45.68      -38.779     -25.939003]
   [ -53.68      -46.779     -33.939003]
   [ -58.68      -51.779     -38.939003]]

  ...

  [[-123.68     -116.779    -103.939   ]
   [-123.68     -116.779    -103.939   ]
   [-123.68     -116.779    -103.939   ]
   ...
   [-123.68     -116.779    -103.939   ]
   [-123.68     -116.779    -103.939   ]
   [-123.68     